spring.application.name=ms-vidasalud-bff
server.port=8080

# ---- Microsoft Entra ID ----
azure.tenant-id=596d0d2f-cf4a-4fd1-8c07-98226aeaeaa5
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${azure.tenant-id}/v2.0
security.jwt.audience=2b3609f5-dacf-4b1b-b9ec-fa0dfd1be88d

# ---- CORS ----
cors.allowed-origins=http://localhost:5173

# ---- Microservicios de dominio ----
services.appointments.url=http://localhost:8081
services.catalog.url=http://localhost:8082

management.endpoints.web.exposure.include=health,info